import img1 from '../Assets/Caravan/1.jfif'
import img2 from '../Assets/Caravan/2.jfif'
import img3 from '../Assets/Caravan/3.jfif'
import img4 from '../Assets/Caravan/4.jfif'
import img5 from '../Assets/Caravan/5.jfif'
import img6 from '../Assets/Caravan/6.jfif'
import img7 from '../Assets/Caravan/7.jfif'
import img8 from '../Assets/Caravan/8.jfif'
import img9 from '../Assets/Caravan/9.jfif'
import img10 from '../Assets/Caravan/10.jfif'
import img11 from '../Assets/Caravan/11.jfif'
import img12 from '../Assets/Caravan/12.jfif'
import img13 from '../Assets/Caravan/13.jfif'
import img14 from '../Assets/Caravan/14.jfif'
import img15 from '../Assets/Caravan/15.jfif'

export const caravans = {
  maindata: [
    {
      id: 1,
      caravan: {
        photo:  `${img1}`,
        name: 'Airstream Classic',
        cost: '₩25,000,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '30 feet',
        weight: '7,788 lbs',
        company: 'Airstream',
        location: '수도권',
        star: '4.8',
      },
    },
    {
      id: 2,
      caravan: {
        photo:  `${img2}`,
        name: 'Jayco Jay Flight',
        cost: '₩22,500,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '28 feet',
        weight: '6,015 lbs',
        company: 'Jayco',
        location: '지방',
        star: '4.5',
      },
    },
    {
      id: 3,
      caravan: {
        photo: `${img3}`,
        name: 'Forest River Salem',
        cost: '₩21,000,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '26 feet',
        weight: '5,890 lbs',
        company: 'Forest River',
        location: '수도권',
        star: '4.3',
      },
    },
    {
      id: 4,
      caravan: {
        photo:  `${img4}`,
        name: 'Keystone Cougar',
        cost: '₩24,500,000',
        type: 'Fifth Wheel',
        people: '4인',
        length: '32 feet',
        weight: '9,680 lbs',
        company: 'Keystone',
        location: '수도권',
        star: '4.7',
      },
    },
    {
      id: 5,
      caravan: {
        photo:  `${img5}`,
        name: 'Winnebago Micro Minnie',
        cost: '₩23,200,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '24 feet',
        weight: '4,480 lbs',
        company: 'Winnebago',
        location: '지방',
        star: '4.6',
      },
    },
    {
      id: 6,
      caravan: {
        photo:  `${img6}`,
        name: 'Grand Design Reflection',
        cost: '₩26,800,000',
        type: 'Fifth Wheel',
        people: '4인',
        length: '34 feet',
        weight: '10,380 lbs',
        company: 'Grand Design',
        location: '수도권',
        star: '4.9',
      },
    },
    {
      id: 7,
      caravan: {
        photo:  `${img7}`,
        name: 'Coachmen Apex Nano',
        cost: '₩20,700,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '22 feet',
        weight: '3,800 lbs',
        company: 'Coachmen',
        location: '지방',
        star: '4.4',
      },
    },
    {
      id: 8,
      caravan: {
        photo:  `${img8}`,
        name: 'Dutchmen Aspen Trail',
        cost: '₩19,500,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '20 feet',
        weight: '3,600 lbs',
        company: 'Dutchmen',
        location: '수도권',
        star: '4.2',
      },
    },
    {
      id: 9,
      caravan: {
        photo:  `${img9}`,
        name: 'Gulf Stream Ameri-Lite',
        cost: '₩18,900,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '18 feet',
        weight: '3,200 lbs',
        company: 'Gulf Stream',
        location: '수도권',
        star: '4.1',
      },
    },
    {
      id: 10,
      caravan: {
        photo:  `${img10}`,
        name: 'Starcraft Autumn Ridge',
        cost: '₩21,300,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '23 feet',
        weight: '4,200 lbs',
        company: 'Starcraft',
        location: '지방',
        star: '4.3',
      },
    },
    {
      id: 11,
      caravan: {
        photo:  `${img11}`,
        name: 'Heartland Prowler',
        cost: '₩20,000,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '21 feet',
        weight: '3,900 lbs',
        company: 'Heartland',
        location: '수도권',
        star: '4.0',
      },
    },
    {
      id: 12,
      caravan: {
        photo:  `${img12}`,
        name: 'KZ Sportsmen Classic',
        cost: '₩19,200,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '19 feet',
        weight: '3,500 lbs',
        company: 'KZ RV',
        location: '지방',
        star: '4.2',
      },
    },
    {
      id: 13,
      caravan: {
        photo:  `${img13}`,
        name: 'Lance Travel Trailer',
        cost: '₩22,800,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '25 feet',
        weight: '4,800 lbs',
        company: 'Lance',
        location: '수도권',
        star: '4.5',
      },
    },
    {
      id: 14,
      caravan: {
        photo:  `${img14}`,
        name: 'NuCamp Tab Teardrop',
        cost: '₩17,500,000',
        type: 'Teardrop Trailer',
        people: '2인',
        length: '15 feet',
        weight: '2,200 lbs',
        company: 'NuCamp',
        location: '지방',
        star: '4.1',
      },
    },
    {
      id: 15,
      caravan: {
        photo:  `${img15}`,
        name: 'Oliver Legacy Elite',
        cost: '₩26,500,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '27 feet',
        weight: '5,500 lbs',
        company: 'Oliver Travel Trailers',
        location: '수도권',
        star: '4.8',
      },
    },
    {
      id: 16,
      caravan: {
        photo:  `${img3}`,
        name: 'Palomino Puma',
        cost: '₩23,000,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '26 feet',
        weight: '4,900 lbs',
        company: 'Palomino RV',
        location: '지방',
        star: '4.4',
      },
    },
    {
      id: 17,
      caravan: {
        photo: `${img6}`,
        name: 'Riverside Retro',
        cost: '₩18,700,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '20 feet',
        weight: '3,400 lbs',
        company: 'Riverside RV',
        location: '수도권',
        star: '4.2',
      },
    },
    {
      id: 18,
      caravan: {
        photo:  `${img9}`,
        name: 'Scamp 16',
        cost: '₩20,300,000',
        type: 'Travel Trailer',
        people: '3인',
        length: '16 feet',
        weight: '2,500 lbs',
        company: 'Scamp Trailers',
        location: '지방',
        star: '4.3',
      },
    },
    {
      id: 19,
      caravan: {
        photo:  `${img12}`,
        name: 'SylvanSport Go',
        cost: '₩15,800,000',
        type: 'Utility Trailer',
        people: '2인',
        length: '12 feet',
        weight: '840 lbs',
        company: 'SylvanSport',
        location: '수도권',
        star: '4.0',
      },
    },
    {
      id: 20,
      caravan: {
        photo:  `${img15}`,
        name: 'Taxa Outdoors Cricket',
        cost: '₩19,900,000',
        type: 'Travel Trailer',
        people: '2인',
        length: '15 feet',
        weight: '1,800 lbs',
        company: 'Taxa Outdoors',
        location: '지방',
        star: '4.1',
      },
    },
    {
      id: 21,
      caravan: {
        photo:  `${img7}`,
        name: 'Travel Lite Aura',
        cost: '₩17,200,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '18 feet',
        weight: '2,995 lbs',
        company: 'Travel Lite RV',
        location: '수도권',
        star: '4.0',
      },
    },
    {
      id: 22,
      caravan: {
        photo:  `${img14}`,
        name: 'Venture RV Sonic',
        cost: '₩21,700,000',
        type: 'Travel Trailer',
        people: '4인',
        length: '23 feet',
        weight: '4,200 lbs',
        company: 'Venture RV',
        location: '지방',
        star: '4.4',
      },
    },
    {
      id: 23,
      caravan: {
        photo:  `${img5}`,
        name: 'Aliner Classic',
        cost: '₩16,900,000',
        type: 'A-Frame Camper',
        people: '2인',
        length: '15 feet',
        weight: '1,590 lbs',
        company: 'Aliner',
        location: '수도권',
        star: '3.9',
      },
    },
    {
      id: 24,
      caravan: {
        photo:  `${img10}`,
        name: 'Casita Spirit Deluxe',
        cost: '₩18,500,000',
        type: 'Travel Trailer',
        people: '3인',
        length: '17 feet',
        weight: '2,480 lbs',
        company: 'Casita Travel Trailers',
        location: '지방',
        star: '4.1',
      },
    },
    {
      id: 25,
      caravan: {
        photo:  `${img15}`,
        name: 'Little Guy Mini Max',
        cost: '₩19,000,000',
        type: 'Teardrop Trailer',
        people: '2인',
        length: '13 feet',
        weight: '2,320 lbs',
        company: 'Little Guy Worldwide',
        location: '수도권',
        star: '4.0',
      },
    },
    // Continue with more caravan data...
  ],
};
