import img1 from '../Assets/UsedCars/1.jfif'
import img2 from '../Assets/UsedCars/2.jfif'
import img3 from '../Assets/UsedCars/3.jfif'
import img4 from '../Assets/UsedCars/4.jfif'
import img5 from '../Assets/UsedCars/5.jfif'
import img6 from '../Assets/UsedCars/6.jfif'
import img7 from '../Assets/UsedCars/7.jfif'
import img8 from '../Assets/UsedCars/8.jfif'
import img9 from '../Assets/UsedCars/9.jfif'
import img10 from '../Assets/UsedCars/10.jfif'
import img11 from '../Assets/UsedCars/11.jfif'
import img12 from '../Assets/UsedCars/12.jfif'
import img13 from '../Assets/UsedCars/13.jfif'
import img14 from '../Assets/UsedCars/14.jfif'
import img15 from '../Assets/UsedCars/15.jfif'

export const usedCars = {
  maindata: [
    {
      id: 11,
      car: {
        photo: `${img1}`,
        name: 'Toyota Land Cruiser',
        cost: '₩13,500,000',
        type: 'SUV',
        license: '1종 보통',
        people: '4인',
        date: '20년 11월',
        company: 'Adventure Motors',
        location: '수도권',
        star: '4.2',
      },
    },
    {
      id: 12,
      car: {
        photo: `${img2}`,
        name: 'Volkswagen California',
        cost: '₩12,200,000',
        type: 'Van',
        license: '1종 보통',
        people: '5인',
        date: '19년 10월',
        company: 'Explore Auto',
        location: '지방',
        star: '4.5',
      },
    },
    {
      id: 13,
      car: {
        photo: `${img3}`,
        name: 'Jeep Wrangler',
        cost: '₩14,500,000',
        type: 'Jeep',
        license: '1종 보통',
        people: '4인',
        date: '20년 08월',
        company: 'Outdoor Motors',
        location: '수도권',
        star: '4.0',
      },
    },
    {
      id: 14,
      car: {
        photo:  `${img4}`,
        name: 'Subaru Outback',
        cost: '₩11,200,000',
        type: 'Station Wagon',
        license: '1종 보통',
        people: '5인',
        date: '19년 12월',
        company: 'Trail Blazers',
        location: '지방',
        star: '4.3',
      },
    },
    {
      id: 15,
      car: {
        photo: `${img5}`,
        name: 'Land Rover Discovery',
        cost: '₩13,700,000',
        type: 'SUV',
        license: '1종 보통',
        people: '4인',
        date: '20년 10월',
        company: 'Camping Wheels',
        location: '수도권',
        star: '4.7',
      },
    },
    {
      id: 16,
      car: {
        photo:  `${img6}`,
        name: 'Mercedes-Benz Sprinter',
        cost: '₩12,800,000',
        type: 'Van',
        license: '1종 보통',
        people: '5인',
        date: '20년 04월',
        company: 'Rugged Rides',
        location: '수도권',
        star: '4.4',
      },
    },
    {
      id: 17,
      car: {
        photo:  `${img7}`,
        name: 'Ford Bronco',
        cost: '₩13,200,000',
        type: 'Jeep',
        license: '1종 보통',
        people: '4인',
        date: '20년 11월',
        company: 'Wilderness Autos',
        location: '지방',
        star: '4.1',
      },
    },
    {
      id: 18,
      car: {
        photo:  `${img8}`,
        name: 'Volvo V60 Cross Country',
        cost: '₩12,700,000',
        type: 'Station Wagon',
        license: '1종 보통',
        people: '5인',
        date: '20년 03월',
        company: 'Adventure Motors',
        location: '수도권',
        star: '4.6',
      },
    },
    {
      id: 19,
      car: {
        photo:  `${img9}`,
        name: 'Toyota 4Runner',
        cost: '₩12,300,000',
        type: 'SUV',
        license: '1종 보통',
        people: '4인',
        date: '19년 07월',
        company: 'Outdoor Motors',
        location: '수도권',
        star: '4.2',
      },
    },
    {
      id: 20,
      car: {
        photo:  `${img10}`,
        name: 'Ford Transit Connect',
        cost: '₩11,800,000',
        type: 'Van',
        license: '1종 보통',
        people: '5인',
        date: '19년 11월',
        company: 'Adventure Motors',
        location: '수도권',
        star: '4.5',
      },
    },
    {
      id: 21,
      car: {
        photo:  `${img11}`,
        name: 'Land Rover Defender',
        cost: '₩14,300,000',
        type: 'Jeep',
        license: '1종 보통',
        people: '4인',
        date: '20년 01월',
        company: 'Outdoor Motors',
        location: '수도권',
        star: '4.0',
      },
    },
    {
      id: 22,
      car: {
        photo: `${img12}`,
        name: 'Subaru Forester',
        cost: '₩13,600,000',
        type: 'Station Wagon',
        license: '1종 보통',
        people: '5인',
        date: '20년 07월',
        company: 'Trail Blazers',
        location: '지방',
        star: '4.3',
      },
    },
    {
      id: 23,
      car: {
        photo:  `${img13}`,
        name: 'Jeep Cherokee',
        cost: '₩13,000,000',
        type: 'SUV',
        license: '1종 보통',
        people: '4인',
        date: '19년 09월',
        company: 'Adventure Motors',
        location: '수도권',
        star: '4.7',
      },
    },
    {
      id: 24,
      car: {
        photo:  `${img14}`,
        name: 'Volkswagen Multivan',
        cost: '₩14,800,000',
        type: 'Van',
        license: '1종 보통',
        people: '5인',
        date: '20년 05월',
        company: 'Explore Auto',
        location: '지방',
        star: '4.4',
      },
    },
    {
      id: 25,
      car: {
        photo:  `${img15}`,
        name: 'Toyota Sequoia',
        cost: '₩13,300,000',
        type: 'SUV',
        license: '1종 보통',
        people: '4인',
        date: '20년 02월',
        company: 'Camping Wheels',
        location: '수도권',
        star: '4.9',
      },
    },
    {
      id: 26,
      car: {
        photo:  `${img2}`,
        name: 'Mercedes-Benz Metris',
        cost: '₩12,600,000',
        type: 'Van',
        license: '1종 보통',
        people: '5인',
        date: '19년 10월',
        company: 'Rugged Rides',
        location: '수도권',
        star: '4.5',
      },
    },
    {
      id: 27,
      car: {
        photo: `${img4}`,
        name: 'Jeep Grand Cherokee',
        cost: '₩14,200,000',
        type: 'SUV',
        license: '1종 보통',
        people: '4인',
        date: '20년 06월',
        company: 'Wilderness Autos',
        location: '지방',
        star: '4.2',
      },
    },
    {
      id: 28,
      car: {
        photo:  `${img6}`,
        name: 'Volvo XC70',
        cost: '₩13,700,000',
        type: 'Station Wagon',
        license: '1종 보통',
        people: '5인',
        date: '20년 04월',
        company: 'Adventure Motors',
        location: '수도권',
        star: '4.6',
      },
    },
    {
      id: 29,
      car: {
        photo:  `${img8}`,
        name: 'Toyota Highlander',
        cost: '₩13,200,000',
        type: 'SUV',
        license: '1종 보통',
        people: '4인',
        date: '19년 08월',
        company: 'Outdoor Motors',
        location: '수도권',
        star: '4.3',
      },
    },
    {
      id: 30,
      car: {
        photo: `${img10}`,
        name: 'Ford Transit',
        cost: '₩12,800,000',
        type: 'Van',
        license: '1종 보통',
        people: '5인',
        date: '20년 03월',
        company: 'Adventure Motors',
        location: '수도권',
        star: '4.5',
      },
    },
  ],
};
